common: &common
  netflix_key: "9bdur3sukahmnwcwf3k3apav"
  netflix_secret: "hY6FdJREWF"
  rotten_tomatoes_key: "9dyme5vu5j487tb22bctmy5c"

development:
  <<: *common

test:
  <<: *common

production:
  <<: *common
