source 'https://rubygems.org'

gem 'rails', '3.2.3'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'rails-api'

gem 'pg'

group :assets do
  gem 'sass-rails',      '~> 3.2.5'
  gem 'coffee-rails',    '~> 3.2.2'
  gem 'bootstrap-sass',  '~> 2.0.2'
  gem 'compass-rails',   '~> 1.0.1'
  gem 'uglifier',        '~> 1.2.4'
  gem 'jquery-rails',    '~> 2.0.2'
  gem 'active_model_serializers',     github: 'teeparham/active_model_serializers', ref: '7f64867f61980b491929fdb881d7b5bc475e0e4f'
  gem 'ember-rails',     github: 'emberjs/ember-rails', ref: '41e09b4e3869aade5a79883bdf6d8392d2fce9d3'
end

group :test, :development do
  gem 'rspec-rails', '~> 2.0'
end

group :development do
  gem 'powder'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
